-- TIMESTAMP WITH TIME ZONE을 TIMESTAMP WITHOUT TIME ZONE으로 변경
-- 이렇게 하면 저장된 값이 그대로 표시됨 (UTC 변환 없음)

-- send_queue 테이블
ALTER TABLE send_queue
  ALTER COLUMN start_time TYPE TIMESTAMP WITHOUT TIME ZONE,
  ALTER COLUMN end_time TYPE TIMESTAMP WITHOUT TIME ZONE,
  ALTER COLUMN start_sent_at TYPE TIMESTAMP WITHOUT TIME ZONE,
  ALTER COLUMN end_sent_at TYPE TIMESTAMP WITHOUT TIME ZONE,
  ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE;

-- status_board 테이블
ALTER TABLE status_board
  ALTER COLUMN start_time TYPE TIMESTAMP WITHOUT TIME ZONE,
  ALTER COLUMN end_time TYPE TIMESTAMP WITHOUT TIME ZONE,
  ALTER COLUMN updated_at TYPE TIMESTAMP WITHOUT TIME ZONE,
  ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE;

-- message_logs 테이블
ALTER TABLE message_logs
  ALTER COLUMN received_at TYPE TIMESTAMP WITHOUT TIME ZONE,
  ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE;

-- slots 테이블
ALTER TABLE slots
  ALTER COLUMN expires_at TYPE TIMESTAMP WITHOUT TIME ZONE,
  ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE,
  ALTER COLUMN updated_at TYPE TIMESTAMP WITHOUT TIME ZONE;

-- users 테이블
ALTER TABLE users
  ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE,
  ALTER COLUMN updated_at TYPE TIMESTAMP WITHOUT TIME ZONE;

-- user_templates 테이블
ALTER TABLE user_templates
  ALTER COLUMN updated_at TYPE TIMESTAMP WITHOUT TIME ZONE,
  ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE;

-- custom_templates 테이블
ALTER TABLE custom_templates
  ALTER COLUMN updated_at TYPE TIMESTAMP WITHOUT TIME ZONE,
  ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE;

-- shop_closing_times 테이블
ALTER TABLE shop_closing_times
  ALTER COLUMN updated_at TYPE TIMESTAMP WITHOUT TIME ZONE,
  ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE;

-- kakao_invite_ids 테이블
ALTER TABLE kakao_invite_ids
  ALTER COLUMN updated_at TYPE TIMESTAMP WITHOUT TIME ZONE,
  ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE;
